name: storage_engine_pocketbase_adapter
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-157.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  storage_engine:
    path: ../storage_engine
  pocketbase: ^0.7.1+1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
